version: '3'
services: 
    web:
        image: infracloudio/csvserver:latest
        ports:
          - "9393:9300"
        environment:
            - CSVSERVER_BORDER=orange
        volumes:
          -  ./inputFile:/csvserver/inputdata
